name: Update Notion News

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  update_news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch News from Notion API
        run: |
          curl -X POST "https://api.notion.com/v1/databases/1a88b79c15b480a6b3a8face84d2a836/query" \
            -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            -o news.json

      - name: Commit and Push JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add news.json
          git commit -m "Update news from Notion API" || exit 0
          git push origin main

